# Generated by Django 2.2.10 on 2020-02-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.IntegerField(choices=[(1, '8-10'), (2, '11-13'), (3, '14-16')], default=1, null=True),
        ),
    ]
