# Generated by Django 2.2.10 on 2020-04-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPassword',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('default_password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
