# Generated by Django 2.2.4 on 2020-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='image',
            field=models.ImageField(blank=True, default='images/KCard.jpg', null=True, upload_to='media/images/'),
        ),
    ]
