# Generated by Django 2.2.10 on 2020-04-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=None, unique=True),
        ),
    ]
