# Generated by Django 2.2.4 on 2020-04-27 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='image_name',
            field=models.CharField(blank=True, default='../account/static/images/KCard.jpg', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='KCardTemplate',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.KindnessCardTemplate'),
        ),
    ]
