# Generated by Django 2.1.7 on 2019-04-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='rewards_active',
            field=models.BooleanField(default=False),
        ),
    ]
