# Generated by Django 2.0.8 on 2019-01-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affirmations',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
