# Generated by Django 2.1.5 on 2019-03-04 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_no', models.AutoField(primary_key=True, serialize=False)),
                ('points_redeemed', models.IntegerField(blank=True, null=True)),
                ('service_used', models.CharField(blank=True, max_length=25, null=True)),
                ('redeem_status', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
