# Generated by Django 2.1.5 on 2019-02-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
