# Generated by Django 2.2.10 on 2020-02-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(blank=True, max_length=500, null=True)),
                ('vision', models.CharField(blank=True, max_length=500, null=True)),
                ('values', models.CharField(blank=True, max_length=500, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
