# Generated by Django 2.1.7 on 2020-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200201_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.IntegerField(choices=[(1, '8-10'), (2, '11-13'), (3, '14-16')], null=True),
        ),
    ]
