# Generated by Django 2.2.10 on 2020-02-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_statements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='publish_date',
        ),
    ]
