# Generated by Django 2.2.10 on 2020-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200227_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultWelcomeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_email', models.CharField(max_length=500)),
            ],
        ),
    ]
