# Generated by Django 2.2.10 on 2020-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_defaultpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.IntegerField(choices=[(1, '6'), (2, '7-10'), (3, '11-13'), (4, '14-16'), (5, '17+')], default=1, null=True),
        ),
    ]
