# Generated by Django 2.0.8 on 2019-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
