# Generated by Django 2.2.4 on 2020-05-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200501_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='image',
            field=models.ImageField(blank=True, default='images/KCard.jpg', null=True, upload_to='images/'),
        ),
    ]
