# Generated by Django 2.2.4 on 2020-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200501_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/KCard.jpg', null=True, upload_to='profile_image/'),
        ),
    ]
