# Generated by Django 2.1.5 on 2019-02-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190206_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyquote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyquote', models.CharField(blank=True, max_length=500, null=True)),
                ('quote_date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Affirmation',
            new_name='Affirmations',
        ),
        migrations.RenameField(
            model_name='affirmations',
            old_name='quote_date',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_date',
        ),
    ]
