# Generated by Django 2.2.10 on 2020-03-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_defaultpassword_defaultwelcomeemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultWelcomeEmail',
            new_name='WelcomeEmail',
        ),
    ]
