# Generated by Django 2.0.8 on 2019-03-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmations',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
