# Generated by Django 2.0.8 on 2019-01-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_inspirationalquotes_quote_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspirationalquotes',
            name='quote_date',
        ),
    ]
