# Generated by Django 2.2.4 on 2020-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200502_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindnesscardtemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
