# Generated by Django 2.2.10 on 2020-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200325_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeemail',
            name='welcome_email',
            field=models.CharField(max_length=1000),
        ),
    ]
