# Generated by Django 2.0.8 on 2019-03-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_affirmations_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affirmations',
            name='description',
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
