# Generated by Django 2.2 on 2020-02-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200201_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.IntegerField(choices=[(1, '8-10'), (2, '11-13'), (3, '14-16')], null=True),
        ),
    ]
