# Generated by Django 2.0.8 on 2019-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dailyquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pre_assessment',
            field=models.DateField(blank=True, default='No', max_length=50, null=True),
        ),
    ]
