# Generated by Django 2.0.8 on 2019-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dailyquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
