# Generated by Django 2.0.8 on 2019-02-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dailyquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_days_to_done', models.IntegerField(default=1)),
                ('nutrition_days_to_done', models.IntegerField(default=1)),
            ],
        ),
    ]
