# Generated by Django 2.0.8 on 2019-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dailyquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inactiveuser',
            fields=[
                ('inactive_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
