# Generated by Django 2.0.8 on 2019-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190302_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pre_assessment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
