# Generated by Django 2.2 on 2020-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200205_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_your_background_color_for_website',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('Purple', 'Purple')], default='pink', max_length=50, null=True),
        ),
    ]
