# Generated by Django 2.0.8 on 2019-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_inactiveuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactiveuser',
            name='set_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
