# Generated by Django 2.0.8 on 2019-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190201_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
