# Generated by Django 2.0.8 on 2019-03-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_parameters_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_days_to_done', models.IntegerField(default=1)),
                ('nutrition_days_to_done', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('current_values', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyquote',
            name='test_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inactiveuser',
            name='up_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
