# Generated by Django 2.2 on 2020-02-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200205_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.IntegerField(choices=[(1, '8-10'), (2, '11-13')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='select_your_background_color_for_website',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange')], default='pink', max_length=50, null=True),
        ),
    ]
