# Generated by Django 2.0.8 on 2019-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_program_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=20, primary_key=True, unique=True),
        ),
    ]
