# Generated by Django 2.0.8 on 2019-03-01 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190228_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactiveuser',
            name='set_days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
