# Generated by Django 2.0.8 on 2019-03-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190313_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testfield2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_to_done', models.IntegerField(default=1)),
                ('nutrition_days_to_done', models.IntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('current_values', models.BooleanField(default=True)),
                ('test4', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyquote',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='inactiveuser',
            name='up_at',
        ),
        migrations.AddField(
            model_name='inactiveuser',
            name='down_at',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='testfield',
            name='test1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
