# Generated by Django 2.0.8 on 2019-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190228_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactiveuser',
            name='set_days',
            field=models.IntegerField(default=1),
        ),
    ]
