# Generated by Django 2.0.8 on 2019-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190313_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindnessMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('from_user', models.CharField(max_length=50)),
                ('to_user', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
