# Generated by Django 2.2 on 2020-02-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200205_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_group',
        ),
    ]
