# Generated by Django 2.0 on 2018-10-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180930_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.IntegerField(blank=True, choices=[(1, '8-10'), (2, '11-13')], null=True),
        ),
    ]
