# Generated by Django 2.2 on 2020-02-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], null=True),
        ),
    ]
