# Generated by Django 2.0.8 on 2019-03-02 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190301_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inactiveuser',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='inactiveuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inactiveuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
