# Generated by Django 2.0.8 on 2019-03-03 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190302_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactiveuser',
            name='set_days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
