# Generated by Django 2.2 on 2020-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(choices=[(1, '7'), (2, '8'), (3, '9'), (4, '10'), (5, '11'), (6, '12'), (7, '13'), (8, '14'), (9, '15'), (10, '16')], null=True),
        ),
    ]
