# Generated by Django 2.0.8 on 2019-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rewardcategory_rewarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_to_clone', models.CharField(max_length=25)),
                ('new_start_date', models.DateField()),
                ('new_program', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
