# Generated by Django 2.0 on 2018-10-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180930_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
