# Generated by Django 2.2 on 2020-02-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200206_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(choices=[(1, '8-10'), (2, '11-13')], null=True),
        ),
    ]
