# Generated by Django 2.0.8 on 2019-03-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190303_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardsNotification',
            fields=[
                ('rewards_notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('rewards_milestone_1', models.IntegerField(default=25)),
                ('rewards_milestone_2', models.IntegerField(default=50)),
                ('rewards_milestone_3', models.IntegerField(default=75)),
                ('rewards_milestone_4', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
