# Generated by Django 2.0.8 on 2018-10-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180930_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', upload_to='profile_image'),
        ),
    ]
