# Generated by Django 2.0.8 on 2019-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_cloneprograminfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcategory',
            name='category',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='reward_category'),
        ),
        migrations.AlterField(
            model_name='rewarditem',
            name='image',
            field=models.ImageField(blank=True, upload_to='reward_item'),
        ),
        migrations.AlterField(
            model_name='rewarditem',
            name='item',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
