# Generated by Django 2.0.8 on 2019-03-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rewardsnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardsNotification',
        ),
    ]
