# Generated by Django 2.2 on 2020-02-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200206_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(choices=[(1, '8'), (2, '9')], null=True),
        ),
    ]
