# Generated by Django 2.2 on 2020-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200206_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(choices=[(1, '8'), (2, '9'), (3, '8'), (4, '10'), (5, '11'), (6, '12'), (7, '13'), (8, '14'), (9, '15'), (10, '16')], default=1, null=True),
        ),
    ]
