# Generated by Django 2.0.8 on 2019-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190330_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcategory',
            name='image',
            field=models.ImageField(blank=True, default='reward_categories/default.png', upload_to='reward_categories/'),
        ),
    ]
