# Generated by Django 2.0.8 on 2019-03-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190330_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardcategory',
            old_name='image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='rewarditem',
            old_name='image',
            new_name='reward_image',
        ),
    ]
