# Generated by Django 2.1.7 on 2019-03-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190330_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='select_your_background_color_for_website',
            field=models.CharField(choices=[('pink', 'Pink'), ('yellow', 'Yellow'), ('green', 'Green'), ('grey', 'Grey')], max_length=50, null=True),
        ),
    ]
