# Generated by Django 2.1.7 on 2019-03-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_profile_select_your_background_color_for_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_your_background_color_for_website',
            field=models.CharField(choices=[('pink', 'Pink'), ('yellow', 'Yellow'), ('green', 'Green'), ('grey', 'Grey')], default='pink', max_length=50, null=True),
        ),
    ]
