# Generated by Django 2.1.7 on 2019-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_kindnessmessage_read_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindnessmessage',
            name='read_message',
            field=models.BooleanField(default=False),
        ),
    ]
