# Generated by Django 2.1.7 on 2019-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20190331_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_your_background_color_for_website',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange')], default='pink', max_length=50, null=True),
        ),
    ]
