<<<<<<< HEAD
# Generated by Django 2.0.6 on 2018-09-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 2.0.8 on 2018-09-19 05:00

from django.db import migrations, models
>>>>>>> 37e980693677088d5189ae40f2b6ad05deb6bcfc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 37e980693677088d5189ae40f2b6ad05deb6bcfc
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=None)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 37e980693677088d5189ae40f2b6ad05deb6bcfc
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=20)),
                ('program_start_date', models.DateField()),
                ('program_end_date', models.DateField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
