# Generated by Django 2.0.8 on 2018-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_validuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='validuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
