# Generated by Django 2.1.7 on 2019-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementalertpage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='announcementalertpage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
