# Generated by Django 2.2.10 on 2020-04-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsindexpage',
            name='display_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
