# Generated by Django 2.0.8 on 2019-03-12 22:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
