# Generated by Django 2.1.7 on 2019-02-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Program'),
        ),
    ]
