# Generated by Django 2.1.7 on 2019-04-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementalertpage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='announcementalertpage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='announcementalertpage',
            name='display_warning',
            field=models.BooleanField(default=False, help_text='Check this box to display warning announcement on the website'),
        ),
    ]
