# Generated by Django 2.2.10 on 2020-02-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('mission', models.CharField(blank=True, max_length=200)),
                ('vision', models.CharField(blank=True, max_length=200)),
                ('values', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='rewardspostpage',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='rewardspostpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicepostpage',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='servicepostpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='testpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='RewardsPostPage',
        ),
        migrations.DeleteModel(
            name='ServicePostPage',
        ),
        migrations.DeleteModel(
            name='TestPage',
        ),
    ]
