# Generated by Django 2.2.10 on 2020-02-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('week', '0002_auto_20190420_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('mission', models.CharField(blank=True, max_length=200)),
                ('vision', models.CharField(blank=True, max_length=200)),
                ('values', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
