# Generated by Django 2.1.7 on 2019-04-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('week', '0002_auto_20190407_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='postassessmentpage',
            name='display_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
