# Generated by Django 2.0.8 on 2019-01-30 01:59

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0002_boilerplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerplate',
            name='heading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='boilerplate',
            name='richtext',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
