# Generated by Django 2.1.7 on 2020-01-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0002_auto_20190420_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessmentpage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='preassessmentpage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
