# Generated by Django 2.1.5 on 2019-02-18 22:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0003_aboutusindexpage_disclaimerlink_extrasindexpage_landingindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclaimerlink',
            name='disclaimer',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disclaimerpage',
            name='disclaimer',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelindexpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programindexpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weekpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
