# Generated by Django 2.1.7 on 2020-01-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0003_auto_20200121_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preassessmentpage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='preassessmentpage',
            name='start_date',
        ),
    ]
