# Generated by Django 2.2.10 on 2020-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0003_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitive',
            name='age_group_content',
            field=models.IntegerField(blank=True, default=0, verbose_name='ENTER 1 IF 6 OR YOUNGER; 2 FOR AGES 7-10; 3 FOR 11-13; 4 FOR 14-16; 5 FOR 17+'),
        ),
    ]
