# Generated by Django 2.0.8 on 2019-03-16 17:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0004_auto_20190313_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingindexpage',
            name='additional',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
