# Generated by Django 2.0.8 on 2019-02-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0004_boilerplate_weeks_to_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programindexpage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
