# Generated by Django 2.0.8 on 2019-02-02 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0005_auto_20190202_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 2, 22, 10, 27, 429182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 2, 22, 10, 27, 429182, tzinfo=utc)),
        ),
    ]
