# Generated by Django 2.0.8 on 2019-02-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0005_extrasindexpage'),
        ('week', '0005_landingindexpage'),
        ('week', '0005_aboutusindexpage'),
    ]

    operations = [
    ]
