# Generated by Django 2.1.5 on 2019-02-23 02:32

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0005_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingindexpage',
            name='description1',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='mental',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='mentaldesc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='nutritional',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='nutritionaldesc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='physical',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='physicaldesc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='relational',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingindexpage',
            name='relationaldesc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
