# Generated by Django 2.1.5 on 2019-02-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0006_auto_20190224_1820'),
        ('week', '0006_auto_20190222_2032'),
    ]

    operations = [
    ]
