# Generated by Django 2.0.8 on 2019-02-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0006_auto_20190202_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='updated_date',
            field=models.DateField(),
        ),
    ]
