# Generated by Django 2.0.8 on 2019-02-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0006_auto_20190218_2101'),
        ('week', '0006_merge_20190217_1413'),
    ]

    operations = [
    ]
