# Generated by Django 2.1.5 on 2019-02-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0007_merge_20190224_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelindexpage',
            name='vertical_image',
        ),
    ]
