# Generated by Django 2.0.8 on 2019-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0007_auto_20190203_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='Points Available',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='DayOfWeek',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='program',
            field=models.CharField(default='', max_length=50),
        ),
    ]
