# Generated by Django 2.0.8 on 2019-02-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0007_merge_20190222_1507'),
        ('week', '0007_merge_20190221_1821'),
        ('week', '0007_merge_20190220_1856'),
    ]

    operations = [
    ]
