# Generated by Django 2.0.8 on 2019-02-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0006_auto_20190218_2101'),
        ('week', '0007_useractivity'),
    ]

    operations = [
    ]
