# Generated by Django 2.0.8 on 2019-02-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0008_auto_20190202_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programindexpage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
