# Generated by Django 2.0.8 on 2019-02-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0008_auto_20190206_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='program',
            new_name='Program',
        ),
    ]
