# Generated by Django 2.0.8 on 2019-02-22 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('week', '0008_emailtemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTemplate',
            new_name='EmailTemplates',
        ),
    ]
