# Generated by Django 2.0.8 on 2019-02-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0008_merge_20190222_1516'),
        ('week', '0009_auto_20190222_1216'),
    ]

    operations = [
    ]
