# Generated by Django 2.0.8 on 2019-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0009_auto_20190206_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='DayOfWeek',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
