# Generated by Django 2.1.7 on 2019-04-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('week', '0010_auto_20190405_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='postassessmentpage',
            name='post_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
