# Generated by Django 2.0.8 on 2019-03-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0010_merge_20190222_1540'),
        ('week', '0010_merge_20190222_1546'),
    ]

    operations = [
    ]
