# Generated by Django 2.0.8 on 2019-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0010_merge_20190222_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplates',
            old_name='individual_message',
            new_name='inactivity_message',
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='subject_for_group',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='subject_for_inactivity',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
