# Generated by Django 2.0.8 on 2019-03-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0011_kindnesscardpage'),
        ('week', '0011_auto_20190303_2031'),
    ]

    operations = [
    ]
