# Generated by Django 2.0.8 on 2019-03-07 01:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0012_merge_20190306_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='rewards_message',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='subject_for_rewards_notification',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
