# Generated by Django 2.0.8 on 2019-03-03 03:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('week', '0012_nutrtiongame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NutrtionGame',
            new_name='NutritionGame',
        ),
    ]
