# Generated by Django 2.0.8 on 2019-03-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0013_auto_20190306_1940'),
        ('week', '0014_merge_20190306_1947'),
    ]

    operations = [
    ]
